menu-name: "Macromolecular complex creator" 
page-name: "Macromolecular Complex Creator" 
type: "model"
help-link: "http://github.com/geneontology/noctua/issues"
javascript:
  - MMCCBundle.js
css:
  - selectize.bootstrap3.css
  - override-selectize.css
